import typedocSidebar from "./docs/api/typedoc-sidebar.cjs";

const sidebars = {
  refSidebar: [
    {
      type: "autogenerated",
      dirName: "ref",
    },
  ],
  apiSidebar: [
    {
      type: "category",
      label: "Modules",
      link: {
        type: "doc",
        id: "api/index",
      },
      items: typedocSidebar,
    },
  ],
};

export default sidebars;
