blank_issues_enabled: false
contact_links:
  - name: Ask a question
    url: https://github.com/operativa-dev/verse-ui/discussions
    about: Ask questions and discuss topics with other community members
  - name: Documentation Request
    url: https://github.com/operativa-dev/verse-ui-docs/issues/new/choose
    about: Request for documentation to be added/altered
