version: "3.8"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile

    volumes:
      - ../..:/workspaces:cached

    command: sleep infinity

    network_mode: service:pg

  pg:
    image: postgres:latest
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./scripts:/scripts
      - ./init-pg.sh:/docker-entrypoint-initdb.d/init-pg.sh
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

  mysql:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - ./scripts:/scripts
      - ./init-mysql.sh:/docker-entrypoint-initdb.d/init-mysql.sh
    environment:
      MYSQL_ROOT_PASSWORD: mysql

volumes:
  postgres-data:
