name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  docs-deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install
        uses: ./.github/composite-actions/install

      - name: Build
        run: pnpm build:docs

      - name: Deploy to GitHub Pages
        run: pnpm deploy:docs
